language: python
python:
  - '3.3'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage wheel

script: sh util/run_tests.sh

after_success:
  - coveralls

deploy:
  provider: pypi
  user: Lucretiel
  password:
    secure: ItMHM+YUcQm3JRQwCpaiSiPSTpwRy33oUQy877x7SJg6Cmd8ImnYbHGn4nBTQd4/Zp3qizmTK8ohE1r+lhvEySO9s8DSit4ArI0/TQbsPfVTUQzzka5ONnZSWwYu8hprUp+fc9MjeydLFioYFg825LX5qL1QCMbk1J2U8G5ohP8=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
